name: CI
on:
  push:
    branches-ignore:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Configure node permissions
        run: |
          chmod -R 777 ./node_modules

      - name: Execute action
        uses: ./

      - name: Run tests against the emulator
        run: yarn test